### ISSUE TITLE
GitPod integration for eclipse-cdt-cloud

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/cdt-cloud#14]
The theia-trace-extension and related repos have been transferred to the eclipse-cdt-cloud GitHub organization. 

Before the transfer, the [GitPod](https://www.gitpod.io/) GitHub app was enabled to use the GitHub integration. It's has been useful for quick code reviews, and the theia-trace-extension uses it for a demo application for user's to try. 

I'd like to enable GitPod GitHub app for the eclipse-cdt-cloud GitHub organization. As far as I know GitHub apps need to be installed on the GitHub organization level and not per repository. 

Are there any objections for me requesting access for eclipse-cdt-cloud (see screenshot below)? Please let me know.

![image](https://user-images.githubusercontent.com/413424/160698228-cca501e7-5fe6-4d4b-863c-dd2efa1253b0.png)

**Comment by jonahgraham** [comment]
No objection. In fact quite the opposite! Go for it.

**Comment by bhufmann** [comment]
Thanks. I've requested access. Should be done soon.

**Comment by bhufmann** [comment]
Permission is granted and the Gitpod app is now installed in the `eclipse-cdt-cloud` organization.

**Comment by bhufmann** [comment]
This works now. See for example https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/731.
