### ISSUE TITLE
Have mailing list and community meetups visible from the webpage.

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse-cdt-cloud/cdt-cloud#16]
Would increase visibility of community efforts.

**Comment by planger** [comment]
Meetups and developer mailing list now mentioned on readme and web page:
  * https://github.com/eclipse-cdt-cloud/cdt-cloud#-meet-the-people-behind-cdtcloud
  * https://www.eclipse.org/cdt-cloud/contact/
