### ISSUE TITLE
cdt-cloud.io should maybe have a link to the code of the blueprint clickable in the line with download

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse-cdt-cloud/cdt-cloud#21]
This could be a good way to make it even clearer that this project is not Open Source in name only.

**Comment by planger** [comment]
Yeah, good idea. We only link the Github repo below or via https://cdt-cloud.io/#blueprint, but a link as a button next to download might be helpful. Thanks!

**Comment by MatthewKhouzam** [comment]
Let's close this? cdt-cloud is gone.
